// =================================================
// ============== THIS IS ROOT LAYOUT ==============
// =================================================

import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Roboto } from "next/font/google";
import { ThemeProvider } from "@/context/theme-provider";
import QueryProvider from "@/context/query-provider";

// Font used
const roboto = Roboto({ subsets: ["latin"], weight: "400" });

// Metadata
export const metadata: Metadata = {
  title: "NextJSBoilerplate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`bg-background ${roboto.className} antialiased`}>
        <QueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
